
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Cek extends javax.swing.JFrame {

    String temp="";
    Double t1, bt, h1;
    /**
     * Creates new form Cek
     */
    public Cek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kberat = new javax.swing.JTextField();
        knama = new javax.swing.JTextField();
        ktinggi = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 180, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Kelamin");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 250, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 110, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tinggi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 150, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Berat Badan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 190, 70, 20);

        kberat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(kberat);
        kberat.setBounds(170, 190, 250, 40);

        knama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(knama);
        knama.setBounds(170, 90, 250, 40);

        ktinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(ktinggi);
        ktinggi.setBounds(170, 140, 250, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(170, 240, 90, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki - laki");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(280, 240, 110, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(60, 290, 80, 40);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 290, 110, 40);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 290, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Berat Badan Ideal Anda adalah :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 350, 240, 17);

        kideal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidealActionPerformed(evt);
            }
        });
        jPanel1.add(kideal);
        kideal.setBounds(240, 340, 160, 30);

        jLabel7.setText("kg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 350, 11, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hasil Diagnosa Kesehatan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 390, 190, 20);

        saran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saranActionPerformed(evt);
            }
        });
        jPanel1.add(saran);
        saran.setBounds(10, 480, 490, 30);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil);
        hasil.setBounds(10, 440, 490, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void kidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidealActionPerformed

    private void saranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saranActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
    if(knama.getText().equals("") ||ktinggi.getText().equals("")||
            kberat.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
    }else if(jRadioButton1.isSelected() ||jRadioButton2.isSelected()){
    try{
        Proses();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Data inputan salah");
    }}  
    else{
    JOptionPane.showMessageDialog(null, "Jenis kelamin belum dipilih");
    }// TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    knama.setText("");
    ktinggi.setText("");
    kberat.setText("");
    buttonGroup1.clearSelection();
    jRadioButton1.setSelected(false);
    jRadioButton2.setSelected(false);
    kideal.setText("");
    hasil.setText("");
    saran.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField kberat;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        
    t1 = Double.valueOf(ktinggi.getText());
    bt = Double.valueOf(kberat.getText());
    
    if (jRadioButton1.isSelected())  {
    h1 = (t1 - 100) * 1;
    } else if (jRadioButton2.isSelected()) {
    h1 = (t1 - 104) * 1;
    }
    temp = Double.toString(h1.intValue());
    
    if (h1 < bt) {
    kideal.setText(temp);
    hasil.setText("Maaf " + knama.getText() + " , Sepertinya anda Overweight :( ");
    saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
    } else if (h1 > bt) {
    kideal.setText(temp);
    hasil.setText("Maaf " + knama.getText() + " , Sepertinya anda Underweight :( ");
    saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
    } else {
    kideal.setText(temp);
    hasil.setText("Hallo " + knama.getText() + " , Berat badan anda sudah ideal :) ");
    saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
    }
    }
}
